### ISSUE TITLE
Standardize URL Path

### ISSUE THREAD

**Issue by chikeichan** [kurumiimari/hsexplorer#2]
To make integration easier for Bob, the url paths should follow patterns set by other block explorer (`hnsfans`, `hnsnetwork`, etc)
- `/address/{address}`
- `/tx/{txHash}`
- `/block/{blockHeight}`
- `/name/{name}`

**Comment by kurumiimari** [comment]
I can add aliases for these.

**Comment by kurumiimari** [comment]
Closed in latest master.
