### ISSUE TITLE
bch

### ISSUE THREAD

**Issue by nelstradamus** [kurumiimari/hsexplorer#24]
so i copied my BCH address from my wallet and for some reason blockexplorer is showing you received it.

**Comment by rithvikvibhu** [comment]
This is a [Handshake](https://handshake.org) explorer, it doesn't show transactions from other chains.

**Comment by nelstradamus** [comment]
Sorry I don’t know what handshake explorer is. I withdrew off a poker site
and copied my address and it sent it to your BCH address.
